name: base-pipeline

on:
  workflow_dispatch:

jobs:
  # Apply Infrastructure configurations when action=='create'.
  snyk:
    name: Code security scan
    uses: Nmbrs/reusable-workflows/.github/workflows/snyk-code-scan.workflow.yaml@demo-sec
    with:
      language-tooling: golang
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}
  
  gitleaks:
    name: gitleaks repository scan
    uses: Nmbrs/reusable-workflows/.github/workflows/gitleaks-repository-scan.workflow.yaml@demo-sec
  
  polaris:
    name: polaris workflow
    uses: Nmbrs/reusable-workflows/.github/workflows/polaris-scan.workflow.yaml@demo-sec
    with:
      polaris_project_name: 'my-project-name'
      polaris_server_url: 'https://my-polaris-url.com'
    secrets:
      polaris_access_token: ${{ secrets.POLARIS_API_TOKEN }}
