name: snyk scan

on:
  workflow_call:
    inputs:
      # valid options: python, dotnet, golang, nodejs, iac, docker
      language-tool:
        description: "Programming language or build tool used"
        required: false
        type: string
        default: dotnet
      target-directory:
        description: "Target working directory"
        required: false
        type: string

    secrets:
      snyk_api token:
        description: Snyk API Token
        required: true

jobs:
  snyk-scan:
    name: snyk scan
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: Run Snyk action for .Net
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_api_token }}
        with:
          command: monitor
      
      - name: Run Snyk action for python
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          command: monitor
      
      # Uploads resulting SARIF file to GitHub Code Scanning
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: snyk.sarif